---
postgres:
  host: "postgres.freydin.space"
  port: "55430"
  user: "admin"
  password: "contrelspawn123"
  name: "onboarding"

neo4j:
  host: "bolt://192.168.1.117"
  port: "7687"
  user: "onboarding"
  password: "contrelspawn123"
  dataBaseName: "roles"

server:
  host: "192.168.1.56"
  port: "8080"